In [1]:
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 14.0 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy

arr = numpy.array([1,2,5,6,7,8])
print(arr[::2])
print(numpy.__version__)

[1 5 7]
1.24.2


In [13]:
"""NumPy is used to work with arrays.
    The array object in NumPy is called ndarray.
    We can create a NumPy ndarray object by using the array() function."""

import numpy

arr = numpy.array([1,2,4,6,7,7]) #can use list
arr2 = numpy.array((1,2,6)) #can use tuple
arr3 = numpy.array({1,2,4,6,7}) #can use set 

print(arr,arr2,arr3)
print(type(arr),type(arr2),type(arr3))

[1 2 4 6 7 7] [1 2 6] {1, 2, 4, 6, 7}
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [44]:
"""Dimensions in Arrays"""
import numpy as np
# ndim is used to know dimension of array
# 0-D Arrays
arr = np.array(42)
print("0-D Array-",arr,", dimension of array =", arr.ndim)

# 1-D Arrays
arr2 = np.array([1,2,5,7])
print("1-D Array-",arr2,", dimension of array =", arr2.ndim)

# 2-D Arrays
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print("2-D Array-",arr3,", dimension of array =", arr3.ndim)

# 3-D arrays
arr4 = np.array([[[1, 2, 3], [4, 7, 9]], [[1, 0, 3], [4, 5, 6]]])
print("3-D Array-",arr4,", dimension of array =", arr4.ndim)


# ndim can be used to create numpy array of desired dimension

arr = np.array([1, 2, 3, 4], ndmin=2)

print(arr,', number of dimensions =', arr.ndim)


0-D Array- 42 , dimension of array = 0
1-D Array- [1 2 5 7] , dimension of array = 1
2-D Array- [[1 2 3]
 [4 5 6]] , dimension of array = 2
3-D Array- [[[1 2 3]
  [4 7 9]]

 [[1 0 3]
  [4 5 6]]] , dimension of array = 3
[[1 2 3 4]] , number of dimensions = 2


In [7]:
import numpy as np

# Access 1-D Arrays
arr = np.array([1,2,3,4,5])
print("2nd element",arr[1])


# Access 2-D Arrays
arr1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr1[0, 1]) #2
print('Last element from 2nd dim: ', arr1[1, -1]) #10

# Access 3-D Arrays
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# 1 ---> [[7, 8, 9], [10, 11, 12]]
# 1 ---> [10, 11, 12]
# 0 ---> 10
print("2nd element on 1st row:",arr2[1,1,0]) #10


2nd element 2
2nd element on 1st row:  2
Last element from 2nd dim:  10
2nd element on 1st row: 10


In [68]:
st = "010110"
count = 0
for index,x in enumerate(st):
    if index in range(len(st)-1):
        
        print(st[index], st[index+1])
        
        if (st[index] == "0" and st[index+1] == "1") or (st[index] == "1" and st[index+1] == "0"):
            print(st, "beautiful")
        else:
            count= count+1
print(count)
        

0 1
010110 beautiful
1 0
010110 beautiful
0 1
010110 beautiful
1 1
1 0
010110 beautiful
1


In [74]:
s = "01010010101"
count = 0
for i in range(1, len(s)):
    if s[i] == s[i-1]:
        count += 1
        s = s[:i] + str(1-int(s[i])) + s[i+1:]
print(count)

6


In [9]:
position = 3
arr = [1, 4, 5, 6, 6, 7, 7] 
x = arr[4:]
arr1 = arr[:4]
print(arr1+x[::-1])

[1, 4, 5, 6, 7, 7, 6]
